# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64.xci
# IP: The module: 'fifo_chipdata_72x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_chipdata_72x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_chipdata_72x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64.xci
# IP: The module: 'fifo_chipdata_72x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_chipdata_72x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_chipdata_72x64/fifo_chipdata_72x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_chipdata_72x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
