# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128.xci
# IP: The module: 'fifo_hitdata_19x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_hitdata_19x128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_hitdata_19x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128.xci
# IP: The module: 'fifo_hitdata_19x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_hitdata_19x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/sphenix/MVTX_dec/MVTX_dec.srcs/sources_1/ip/fifo_hitdata_19x128/fifo_hitdata_19x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_hitdata_19x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
