-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cluster_cluster_algo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    buf_in_dout : IN STD_LOGIC_VECTOR (18 downto 0);
    buf_in_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    buf_in_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    buf_in_empty_n : IN STD_LOGIC;
    buf_in_read : OUT STD_LOGIC;
    buf_out_din : OUT STD_LOGIC_VECTOR (20 downto 0);
    buf_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    buf_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    buf_out_full_n : IN STD_LOGIC;
    buf_out_write : OUT STD_LOGIC );
end;


architecture behav of cluster_cluster_algo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal clusterConstituents_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal clusterConstituents_ce0 : STD_LOGIC;
    signal clusterConstituents_we0 : STD_LOGIC;
    signal clusterConstituents_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal clusterConstituents_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal clusterConstituents_first_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal clusterConstituents_first_V_ce0 : STD_LOGIC;
    signal clusterConstituents_first_V_we0 : STD_LOGIC;
    signal clusterConstituents_first_V_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal clusterConstituents_first_V_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buf_in_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_nbreadreq_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal buf_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal lhs_2_fu_294_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal lhs_2_reg_585 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_first_V_fu_298_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_first_V_reg_590 : STD_LOGIC_VECTOR (8 downto 0);
    signal lhs_fu_308_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_reg_595 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_1_fu_312_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal lhs_1_reg_600 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_32_fu_320_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_32_reg_605 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln102_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln102_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln104_fu_356_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln104_reg_614 : STD_LOGIC_VECTOR (3 downto 0);
    signal clusterConstituents_addr_reg_621 : STD_LOGIC_VECTOR (3 downto 0);
    signal clusterConstituents_first_V_addr_reg_626 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln462_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln462_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln111_fu_407_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln111_reg_648 : STD_LOGIC_VECTOR (2 downto 0);
    signal rhs_reg_653 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ret_V_2_fu_417_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ret_V_2_reg_661 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_441_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock_reg_681 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal i_fu_545_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_4_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_idle : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_ready : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out_ap_vld : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out_ap_vld : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_ce0 : STD_LOGIC;
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_ce0 : STD_LOGIC;
    signal grp_writeCluster_fu_250_ap_start : STD_LOGIC;
    signal grp_writeCluster_fu_250_ap_done : STD_LOGIC;
    signal grp_writeCluster_fu_250_ap_idle : STD_LOGIC;
    signal grp_writeCluster_fu_250_ap_ready : STD_LOGIC;
    signal grp_writeCluster_fu_250_index : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_writeCluster_fu_250_clusterConstituents_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_writeCluster_fu_250_clusterConstituents_ce0 : STD_LOGIC;
    signal grp_writeCluster_fu_250_clusterConstituents_we0 : STD_LOGIC;
    signal grp_writeCluster_fu_250_clusterConstituents_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_writeCluster_fu_250_clusterConstituents_first_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_writeCluster_fu_250_clusterConstituents_first_V_ce0 : STD_LOGIC;
    signal grp_writeCluster_fu_250_clusterConstituents_first_V_we0 : STD_LOGIC;
    signal grp_writeCluster_fu_250_clusterConstituents_first_V_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_writeCluster_fu_250_ap_return_0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_writeCluster_fu_250_ap_return_1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_writeCluster_fu_250_ap_return_2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_writeCluster_fu_250_ap_return_3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_reg_191 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal j_reg_203 : STD_LOGIC_VECTOR (2 downto 0);
    signal adjacentPixel_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln19_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deltaColumn_V_reg_214 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_5_ph_reg_226 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1081_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln111_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal nConstituents_V_loc_fu_106 : STD_LOGIC_VECTOR (3 downto 0);
    signal nConstituents_V_4_loc_fu_102 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_writeCluster_fu_250_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal zext_ln104_fu_362_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln114_1_fu_395_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln149_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_s_fu_532_p5 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_7_fu_557_p5 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_324_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_fu_316_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_340_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_348_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln462_1_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln462_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln114_fu_386_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln114_fu_390_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln232_1_fu_413_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_422_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln232_fu_438_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_446_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_460_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln1085_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1085_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_487_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln1085_1_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1085_2_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln141_fu_514_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln149_fu_521_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cluster_cluster_algo_Pipeline_VITIS_LOOP_141_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sub_ln104 : IN STD_LOGIC_VECTOR (3 downto 0);
        nConstituents_V_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        nConstituents_V_out_ap_vld : OUT STD_LOGIC;
        nConstituents_V_4_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        nConstituents_V_4_out_ap_vld : OUT STD_LOGIC;
        clusterConstituents_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        clusterConstituents_ce0 : OUT STD_LOGIC;
        clusterConstituents_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        clusterConstituents_first_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        clusterConstituents_first_V_ce0 : OUT STD_LOGIC;
        clusterConstituents_first_V_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cluster_writeCluster IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        index : IN STD_LOGIC_VECTOR (0 downto 0);
        clusterConstituents_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        clusterConstituents_ce0 : OUT STD_LOGIC;
        clusterConstituents_we0 : OUT STD_LOGIC;
        clusterConstituents_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        clusterConstituents_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        clusterConstituents_first_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        clusterConstituents_first_V_ce0 : OUT STD_LOGIC;
        clusterConstituents_first_V_we0 : OUT STD_LOGIC;
        clusterConstituents_first_V_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        clusterConstituents_first_V_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cluster_cluster_algo_clusterConstituents_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (9 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component cluster_cluster_algo_clusterConstituents_first_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (8 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;



begin
    clusterConstituents_U : component cluster_cluster_algo_clusterConstituents_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 12,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => clusterConstituents_address0,
        ce0 => clusterConstituents_ce0,
        we0 => clusterConstituents_we0,
        d0 => clusterConstituents_d0,
        q0 => clusterConstituents_q0);

    clusterConstituents_first_V_U : component cluster_cluster_algo_clusterConstituents_first_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 9,
        AddressRange => 12,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => clusterConstituents_first_V_address0,
        ce0 => clusterConstituents_first_V_ce0,
        we0 => clusterConstituents_first_V_we0,
        d0 => clusterConstituents_first_V_d0,
        q0 => clusterConstituents_first_V_q0);

    grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239 : component cluster_cluster_algo_Pipeline_VITIS_LOOP_141_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start,
        ap_done => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done,
        ap_idle => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_idle,
        ap_ready => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_ready,
        sub_ln104 => sub_ln104_reg_614,
        nConstituents_V_out => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out,
        nConstituents_V_out_ap_vld => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out_ap_vld,
        nConstituents_V_4_out => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out,
        nConstituents_V_4_out_ap_vld => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out_ap_vld,
        clusterConstituents_address0 => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_address0,
        clusterConstituents_ce0 => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_ce0,
        clusterConstituents_q0 => clusterConstituents_q0,
        clusterConstituents_first_V_address0 => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_address0,
        clusterConstituents_first_V_ce0 => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_ce0,
        clusterConstituents_first_V_q0 => clusterConstituents_first_V_q0,
        ap_return => grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_return);

    grp_writeCluster_fu_250 : component cluster_writeCluster
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_writeCluster_fu_250_ap_start,
        ap_done => grp_writeCluster_fu_250_ap_done,
        ap_idle => grp_writeCluster_fu_250_ap_idle,
        ap_ready => grp_writeCluster_fu_250_ap_ready,
        index => grp_writeCluster_fu_250_index,
        clusterConstituents_address0 => grp_writeCluster_fu_250_clusterConstituents_address0,
        clusterConstituents_ce0 => grp_writeCluster_fu_250_clusterConstituents_ce0,
        clusterConstituents_we0 => grp_writeCluster_fu_250_clusterConstituents_we0,
        clusterConstituents_d0 => grp_writeCluster_fu_250_clusterConstituents_d0,
        clusterConstituents_q0 => clusterConstituents_q0,
        clusterConstituents_first_V_address0 => grp_writeCluster_fu_250_clusterConstituents_first_V_address0,
        clusterConstituents_first_V_ce0 => grp_writeCluster_fu_250_clusterConstituents_first_V_ce0,
        clusterConstituents_first_V_we0 => grp_writeCluster_fu_250_clusterConstituents_first_V_we0,
        clusterConstituents_first_V_d0 => grp_writeCluster_fu_250_clusterConstituents_first_V_d0,
        clusterConstituents_first_V_q0 => clusterConstituents_first_V_q0,
        ap_return_0 => grp_writeCluster_fu_250_ap_return_0,
        ap_return_1 => grp_writeCluster_fu_250_ap_return_1,
        ap_return_2 => grp_writeCluster_fu_250_ap_return_2,
        ap_return_3 => grp_writeCluster_fu_250_ap_return_3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_fu_272_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_ready = ap_const_logic_1)) then 
                    grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_writeCluster_fu_250_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_writeCluster_fu_250_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                    grp_writeCluster_fu_250_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_writeCluster_fu_250_ap_ready = ap_const_logic_1)) then 
                    grp_writeCluster_fu_250_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    deltaColumn_V_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln462_fu_380_p2 = ap_const_lv1_1))) then 
                deltaColumn_V_reg_214 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and ((ap_const_lv1_0 = and_ln19_fu_476_p2) or (ap_const_lv1_0 = adjacentPixel_fu_502_p2)))) then 
                deltaColumn_V_reg_214 <= ret_V_fu_441_p2;
            end if; 
        end if;
    end process;

    i_2_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                i_2_reg_191 <= i_4_fu_551_p2;
            elsif ((not(((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_2_reg_191 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_5_ph_reg_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln111_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln1081_fu_432_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fu_272_p2 = ap_const_lv1_1)))) then 
                i_5_ph_reg_226 <= i_2_reg_191;
            elsif ((not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                i_5_ph_reg_226 <= i_fu_545_p2;
            end if; 
        end if;
    end process;

    j_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln462_fu_380_p2 = ap_const_lv1_1))) then 
                j_reg_203 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and ((ap_const_lv1_0 = and_ln19_fu_476_p2) or (ap_const_lv1_0 = adjacentPixel_fu_502_p2)))) then 
                j_reg_203 <= add_ln111_reg_648;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln111_reg_648 <= add_ln111_fu_407_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln102_fu_334_p2 = ap_const_lv1_1))) then
                    clusterConstituents_addr_reg_621(3 downto 1) <= zext_ln104_fu_362_p1(4 - 1 downto 0)(3 downto 1);
                    clusterConstituents_first_V_addr_reg_626(3 downto 1) <= zext_ln104_fu_362_p1(4 - 1 downto 0)(3 downto 1);
                    sub_ln104_reg_614(3 downto 1) <= sub_ln104_fu_356_p2(3 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                empty_32_reg_605 <= empty_32_fu_320_p1;
                icmp_ln102_reg_610 <= icmp_ln102_fu_334_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    lhs_1_reg_600(8 downto 0) <= lhs_1_fu_312_p1(8 downto 0);
                lhs_2_reg_585 <= lhs_2_fu_294_p1;
                    lhs_reg_595(9 downto 0) <= lhs_fu_308_p1(9 downto 0);
                tmp_first_V_reg_590 <= buf_in_dout(18 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out_ap_vld = ap_const_logic_1))) then
                nConstituents_V_4_loc_fu_102 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out_ap_vld = ap_const_logic_1))) then
                nConstituents_V_loc_fu_106 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_nConstituents_V_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                or_ln462_reg_631 <= or_ln462_fu_380_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fu_272_p2 = ap_const_lv1_0))) then
                ret_V_2_reg_661 <= ret_V_2_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                rhs_reg_653 <= clusterConstituents_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                targetBlock_reg_681 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_return;
            end if;
        end if;
    end process;
    lhs_reg_595(10) <= '0';
    lhs_1_reg_600(9) <= '0';
    sub_ln104_reg_614(0) <= '0';
    clusterConstituents_addr_reg_621(0) <= '0';
    clusterConstituents_first_V_addr_reg_626(0) <= '0';

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, buf_in_empty_n, buf_out_full_n, ap_CS_fsm_state2, tmp_nbreadreq_fu_110_p3, ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state3, icmp_ln102_fu_334_p2, or_ln462_fu_380_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, grp_fu_272_p2, ap_CS_fsm_state7, ap_CS_fsm_state9, grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done, grp_writeCluster_fu_250_ap_done, adjacentPixel_fu_502_p2, and_ln19_fu_476_p2, icmp_ln1081_fu_432_p2, icmp_ln111_fu_401_p2, ap_CS_fsm_state15)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_110_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif ((not(((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln102_fu_334_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln462_fu_380_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln111_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln1081_fu_432_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fu_272_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((icmp_ln1081_fu_432_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fu_272_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and ((ap_const_lv1_0 = and_ln19_fu_476_p2) or (ap_const_lv1_0 = adjacentPixel_fu_502_p2)))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if ((not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_fu_272_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if ((not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln111_fu_407_p2 <= std_logic_vector(unsigned(j_reg_203) + unsigned(ap_const_lv3_1));
    add_ln114_fu_390_p2 <= std_logic_vector(unsigned(sub_ln104_reg_614) + unsigned(zext_ln114_fu_386_p1));
    add_ln149_fu_521_p2 <= std_logic_vector(unsigned(sub_ln104_reg_614) + unsigned(select_ln141_fu_514_p3));
    adjacentPixel_fu_502_p2 <= (icmp_ln1085_2_fu_496_p2 and icmp_ln1085_1_fu_482_p2);
    and_ln19_fu_476_p2 <= (xor_ln1085_fu_454_p2 and icmp_ln1085_fu_470_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(buf_out_full_n, grp_writeCluster_fu_250_ap_done)
    begin
        if (((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state17_blk_assign_proc : process(buf_out_full_n, grp_writeCluster_fu_250_ap_done)
    begin
        if (((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state17_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state17_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(buf_in_empty_n, tmp_nbreadreq_fu_110_p3)
    begin
        if (((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done)
    begin
        if ((grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(buf_in_empty_n, tmp_nbreadreq_fu_110_p3)
    begin
                ap_block_state2 <= ((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_fu_272_p2, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_fu_272_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    buf_in_blk_n_assign_proc : process(buf_in_empty_n, ap_CS_fsm_state2, tmp_nbreadreq_fu_110_p3)
    begin
        if (((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buf_in_blk_n <= buf_in_empty_n;
        else 
            buf_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    buf_in_read_assign_proc : process(buf_in_empty_n, ap_CS_fsm_state2, tmp_nbreadreq_fu_110_p3)
    begin
        if ((not(((tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (buf_in_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buf_in_read <= ap_const_logic_1;
        else 
            buf_in_read <= ap_const_logic_0;
        end if; 
    end process;


    buf_out_blk_n_assign_proc : process(buf_out_full_n, ap_CS_fsm_state12, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buf_out_blk_n <= buf_out_full_n;
        else 
            buf_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    buf_out_din_assign_proc : process(buf_out_full_n, ap_CS_fsm_state12, ap_CS_fsm_state17, grp_writeCluster_fu_250_ap_done, tmp_s_fu_532_p5, tmp_7_fu_557_p5)
    begin
        if (not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0)))) then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                buf_out_din <= tmp_7_fu_557_p5;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                buf_out_din <= tmp_s_fu_532_p5;
            else 
                buf_out_din <= "XXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            buf_out_din <= "XXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_out_write_assign_proc : process(buf_out_full_n, ap_CS_fsm_state12, ap_CS_fsm_state17, grp_writeCluster_fu_250_ap_done)
    begin
        if (((not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state17)) or (not(((buf_out_full_n = ap_const_logic_0) or (grp_writeCluster_fu_250_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12)))) then 
            buf_out_write <= ap_const_logic_1;
        else 
            buf_out_write <= ap_const_logic_0;
        end if; 
    end process;


    clusterConstituents_address0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state3, clusterConstituents_addr_reg_621, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_address0, grp_writeCluster_fu_250_clusterConstituents_address0, zext_ln104_fu_362_p1, zext_ln114_1_fu_395_p1, zext_ln149_fu_526_p1, ap_CS_fsm_state10, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            clusterConstituents_address0 <= ap_const_lv4_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusterConstituents_address0 <= zext_ln149_fu_526_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterConstituents_address0 <= zext_ln114_1_fu_395_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            clusterConstituents_address0 <= clusterConstituents_addr_reg_621;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterConstituents_address0 <= zext_ln104_fu_362_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_address0 <= grp_writeCluster_fu_250_clusterConstituents_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            clusterConstituents_address0 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_address0;
        else 
            clusterConstituents_address0 <= "XXXX";
        end if; 
    end process;


    clusterConstituents_ce0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_ce0, grp_writeCluster_fu_250_clusterConstituents_ce0, ap_CS_fsm_state10, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            clusterConstituents_ce0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_ce0 <= grp_writeCluster_fu_250_clusterConstituents_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            clusterConstituents_ce0 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_ce0;
        else 
            clusterConstituents_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusterConstituents_d0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, lhs_2_reg_585, ap_CS_fsm_state4, grp_writeCluster_fu_250_clusterConstituents_d0, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            clusterConstituents_d0 <= lhs_2_reg_585;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_d0 <= grp_writeCluster_fu_250_clusterConstituents_d0;
        else 
            clusterConstituents_d0 <= "XXXXXXXXXX";
        end if; 
    end process;


    clusterConstituents_first_V_address0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state3, clusterConstituents_first_V_addr_reg_626, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_address0, grp_writeCluster_fu_250_clusterConstituents_first_V_address0, zext_ln104_fu_362_p1, zext_ln114_1_fu_395_p1, zext_ln149_fu_526_p1, ap_CS_fsm_state10, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            clusterConstituents_first_V_address0 <= ap_const_lv4_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            clusterConstituents_first_V_address0 <= zext_ln149_fu_526_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            clusterConstituents_first_V_address0 <= zext_ln114_1_fu_395_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            clusterConstituents_first_V_address0 <= clusterConstituents_first_V_addr_reg_626;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            clusterConstituents_first_V_address0 <= zext_ln104_fu_362_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_first_V_address0 <= grp_writeCluster_fu_250_clusterConstituents_first_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            clusterConstituents_first_V_address0 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_address0;
        else 
            clusterConstituents_first_V_address0 <= "XXXX";
        end if; 
    end process;


    clusterConstituents_first_V_ce0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_ce0, grp_writeCluster_fu_250_clusterConstituents_first_V_ce0, ap_CS_fsm_state10, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            clusterConstituents_first_V_ce0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_first_V_ce0 <= grp_writeCluster_fu_250_clusterConstituents_first_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            clusterConstituents_first_V_ce0 <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_clusterConstituents_first_V_ce0;
        else 
            clusterConstituents_first_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clusterConstituents_first_V_d0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, tmp_first_V_reg_590, ap_CS_fsm_state4, grp_writeCluster_fu_250_clusterConstituents_first_V_d0, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            clusterConstituents_first_V_d0 <= tmp_first_V_reg_590;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_first_V_d0 <= grp_writeCluster_fu_250_clusterConstituents_first_V_d0;
        else 
            clusterConstituents_first_V_d0 <= "XXXXXXXXX";
        end if; 
    end process;


    clusterConstituents_first_V_we0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, icmp_ln102_reg_610, or_ln462_fu_380_p2, or_ln462_reg_631, ap_CS_fsm_state4, grp_writeCluster_fu_250_clusterConstituents_first_V_we0, ap_CS_fsm_state10)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln462_reg_631 = ap_const_lv1_1) and (icmp_ln102_reg_610 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln462_fu_380_p2 = ap_const_lv1_0)))) then 
            clusterConstituents_first_V_we0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_first_V_we0 <= grp_writeCluster_fu_250_clusterConstituents_first_V_we0;
        else 
            clusterConstituents_first_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    clusterConstituents_we0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, icmp_ln102_reg_610, or_ln462_fu_380_p2, or_ln462_reg_631, ap_CS_fsm_state4, grp_writeCluster_fu_250_clusterConstituents_we0, ap_CS_fsm_state10)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state10) and (or_ln462_reg_631 = ap_const_lv1_1) and (icmp_ln102_reg_610 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (or_ln462_fu_380_p2 = ap_const_lv1_0)))) then 
            clusterConstituents_we0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            clusterConstituents_we0 <= grp_writeCluster_fu_250_clusterConstituents_we0;
        else 
            clusterConstituents_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_32_fu_320_p1 <= i_2_reg_191(1 - 1 downto 0);
    empty_fu_316_p1 <= i_2_reg_191(3 - 1 downto 0);
    grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start <= grp_cluster_algo_Pipeline_VITIS_LOOP_141_2_fu_239_ap_start_reg;
    grp_fu_260_p2 <= "1" when (clusterConstituents_q0 = ap_const_lv10_0) else "0";
    grp_fu_266_p2 <= "1" when (clusterConstituents_first_V_q0 = ap_const_lv9_0) else "0";
    grp_fu_272_p2 <= (grp_fu_266_p2 and grp_fu_260_p2);
    grp_writeCluster_fu_250_ap_start <= grp_writeCluster_fu_250_ap_start_reg;

    grp_writeCluster_fu_250_index_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state17, empty_32_reg_605)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            grp_writeCluster_fu_250_index <= ap_const_lv1_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_writeCluster_fu_250_index <= empty_32_reg_605;
        else 
            grp_writeCluster_fu_250_index <= "X";
        end if; 
    end process;

    i_4_fu_551_p2 <= std_logic_vector(unsigned(i_5_ph_reg_226) + unsigned(ap_const_lv32_1));
    i_fu_545_p2 <= std_logic_vector(unsigned(i_2_reg_191) + unsigned(ap_const_lv32_FFFFFFFF));
    icmp_ln102_fu_334_p2 <= "1" when (tmp_5_fu_324_p4 = ap_const_lv31_0) else "0";
    icmp_ln1081_fu_432_p2 <= "1" when (signed(tmp_6_fu_422_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln1085_1_fu_482_p2 <= "1" when (signed(ret_V_2_reg_661) > signed(ap_const_lv10_3FE)) else "0";
    icmp_ln1085_2_fu_496_p2 <= "1" when (signed(tmp_10_fu_487_p4) < signed(ap_const_lv9_1)) else "0";
    icmp_ln1085_fu_470_p2 <= "1" when (signed(tmp_9_fu_460_p4) < signed(ap_const_lv10_1)) else "0";
    icmp_ln111_fu_401_p2 <= "1" when (j_reg_203 = ap_const_lv3_6) else "0";
    icmp_ln462_1_fu_374_p2 <= "0" when (clusterConstituents_first_V_q0 = ap_const_lv9_0) else "1";
    icmp_ln462_fu_368_p2 <= "0" when (clusterConstituents_q0 = ap_const_lv10_0) else "1";

    internal_ap_ready_assign_proc : process(grp_fu_272_p2, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_fu_272_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    lhs_1_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_first_V_fu_298_p4),10));
    lhs_2_fu_294_p1 <= buf_in_dout(10 - 1 downto 0);
    lhs_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_2_fu_294_p1),11));
    or_ln462_fu_380_p2 <= (icmp_ln462_fu_368_p2 or icmp_ln462_1_fu_374_p2);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    ret_V_2_fu_417_p2 <= std_logic_vector(unsigned(lhs_1_reg_600) - unsigned(zext_ln232_1_fu_413_p1));
    ret_V_fu_441_p2 <= std_logic_vector(unsigned(lhs_reg_595) - unsigned(zext_ln232_fu_438_p1));
    select_ln141_fu_514_p3 <= 
        nConstituents_V_loc_fu_106 when (targetBlock_reg_681(0) = '1') else 
        nConstituents_V_4_loc_fu_102;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln104_fu_356_p2 <= std_logic_vector(unsigned(tmp_2_fu_340_p3) - unsigned(tmp_3_fu_348_p3));
    tmp_10_fu_487_p4 <= ret_V_2_reg_661(9 downto 1);
    tmp_2_fu_340_p3 <= (empty_32_fu_320_p1 & ap_const_lv3_0);
    tmp_3_fu_348_p3 <= (empty_fu_316_p1 & ap_const_lv1_0);
    tmp_5_fu_324_p4 <= i_2_reg_191(31 downto 1);
    tmp_6_fu_422_p4 <= deltaColumn_V_reg_214(10 downto 1);
    tmp_7_fu_557_p5 <= (((grp_writeCluster_fu_250_ap_return_3 & grp_writeCluster_fu_250_ap_return_2) & grp_writeCluster_fu_250_ap_return_1) & grp_writeCluster_fu_250_ap_return_0);
    tmp_8_fu_446_p3 <= ret_V_fu_441_p2(10 downto 10);
    tmp_9_fu_460_p4 <= ret_V_fu_441_p2(10 downto 1);
    tmp_first_V_fu_298_p4 <= buf_in_dout(18 downto 10);
    tmp_nbreadreq_fu_110_p3 <= (0=>(buf_in_empty_n), others=>'-');
    tmp_s_fu_532_p5 <= (((grp_writeCluster_fu_250_ap_return_3 & grp_writeCluster_fu_250_ap_return_2) & grp_writeCluster_fu_250_ap_return_1) & grp_writeCluster_fu_250_ap_return_0);
    xor_ln1085_fu_454_p2 <= (tmp_8_fu_446_p3 xor ap_const_lv1_1);
    zext_ln104_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln104_fu_356_p2),64));
    zext_ln114_1_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln114_fu_390_p2),64));
    zext_ln114_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_203),4));
    zext_ln149_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln149_fu_521_p2),64));
    zext_ln232_1_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(clusterConstituents_first_V_q0),10));
    zext_ln232_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_reg_653),11));
end behav;
